#!/usr/bin/expect

set timeout 20

set ip 192.168.50.150
set port 60000
set user admin
set password password

#set ip [lindex $argv 0]
#set port [lindex $argv 1]
#set user [lindex $argv 2]
#set password [lindex $argv 3]

log_user 0;
spawn telnet $ip $port

sleep .1
send "$user\n"
sleep .1
expect "Password:"
send "$password\n";
sleep .1
send "enable\n\n"
expect {
    "#" {
        send "show poe port info all\n"
    }
}


send "quit\n"
send "n"

interact